apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-client-golang
  labels:
    app: prometheus-client-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-client-golang
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: prometheus-client-golang
    spec:
      containers:
      - name: app
        image: prometheus-client-golang
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
        livenessProbe:
          httpGet:
           path: /metrics
           port: 8080
      # imagePullSecrets:
      # - name: acr-srcrdev-auth
      restartPolicy: Always